### ISSUE TITLE
Suggestion refactor locations.py to remove pyproj dependency

### ISSUE THREAD

**Issue by micahcochran** [jekirl/poketrainer#410]
[pgoapi/location.py](https://github.com/j-e-k/poketrainer/blob/master/pgoapi/location.py) adds a required dependency for pyproj.  Pyproj depends upon the C library PROJ.4.  This project barely uses any of the features of pyproj library. (At a glance, geopy seems to have a more pythonic interface than the pyproj.Geod class.)

I suggest refactoring the get_increments() function to use [geographiclib](http://geographiclib.sourceforge.net/) (link on [PyPi](https://pypi.python.org/pypi/geographiclib/1.46.3)), which is a fully python library.  The [Computing waypoints example](http://geographiclib.sourceforge.net/html/python/examples.html#computing-waypoints) seems to be very similar to what you are trying to accomplish with the get_increments() function.

This refactor might make your project slightly easier to install.

**Comment by stolencatkarma** [comment]
feel free to take this on. submit a pull request and we'll look it over.

**Comment by micahcochran** [comment]
I don't use this software. I am a collaborator for pyproj.  Please don't let me get in the way of someone taking on this task.    I do hope there is enough information that this would be a fairly straightforward change.

**Comment by stolencatkarma** [comment]
Thanks for the input then! I'll look into this.
